name: Test  Action

on: [push]

env:
  BUILDBEAR_BASE_URL: "https://api.test.buildbear.io"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache Foundry repository
      - name: Cache Foundry repository
        uses: actions/cache@v3
        with:
          path: foundry
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry/.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      # Cache build artifacts
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: $HOME/.config/.foundry/bin
          key: ${{ runner.os }}-forge-${{ hashFiles('foundry/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      - name: Clone Foundry repository
        run: |
          if [ ! -d "foundry" ]; then
            git clone https://github.com/BuildBearLabs/foundry.git
          fi
        shell: bash

      - name: Clone Hardhat-BuildBear
        run: |
          if [ ! -d "Hardhat-BuildBear" ]; then
          git clone https://github.com/BuildBearLabs/Hardhat-BuildBear.git
          fi
        shell: bash
      - name: Install dependencies
        run: npm ci

      - name: Build Foundry from source
        run: |
          cd foundry
          cargo build
          mkdir -p $HOME/.config/.foundry/bin
          cp target/debug/forge $HOME/.config/.foundry/bin/
          echo "PATH=$HOME/.config/.foundry/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Show Forge version
        run: forge --version

      - name: Make bbOut dir
        run: mkdir bbOut
        shell: bash

      - name: Derive private key from mnemonic
        shell: bash
        env:
          # ensure cast is available
          PATH: $HOME/.config/.foundry/bin:$PATH
        run: |
          echo "Deriving private key from your mnemonic…"
          DERIVED_PK=$(cast wallet private-key "$(MNEMONIC)")
          # override MNEMONIC so Makefile’s --mnemonics="$(MNEMONIC)" picks up the private key
          echo "MNEMONIC=${DERIVED_PK}" >> $GITHUB_ENV

      - name: test_ci
        uses: BuildBearLabs/buildbear_x_action@feat/modify-payload-with-new-api
        with:
          network: |
            [
              {
                "chainId": 1
              }
            ]

          deploy-command: "make exe"
          buildbear-token: "f0e3ecb8f-c67f-42dd-b5e3-32780dfeac08"
        env:
          API_KEY: "f0e3ecb8f-c67f-42dd-b5e3-32780dfeac08"
          MNEMONIC: $(MNEMONIC)
