name: Test  Action

on: [push]

# Workflow

env:
  BUILDBEAR_BASE_URL: "https://api.test.buildbear.io"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clone Hardhat-BuildBear
        run: |
          if [ ! -d "Hardhat-BuildBear" ]; then
          git clone https://github.com/BuildBearLabs/Hardhat-BuildBear.git
          fi
        shell: bash

      - name: Make bbOut dir
        run: mkdir bbOut
        shell: bash

      - name: test_ci
        uses: BuildBearLabs/buildbear_x_action@feat/modify-payload-with-new-api
        with:
          network: |
            [
              {
                "chainId": 1
              }
            ]

          deploy-command: "make exe"
          buildbear-token: "${{secrets.CICD_BUILDBEAR_TOKEN}}"
        env:
          API_KEY: "${{secrets.CICD_BUILDBEAR_TOKEN}}"
